
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='xepmts_server',
    version='0.1.3',
    description='Top-level package for xepmts-server.',
    python_requires='>=3.7.1',
    project_urls={"homepage": "https://github.com/jmosbacher/xepmts_server"},
    author='Yossi Mosbacher',
    author_email='joe.mosbacher@gmail.com',
    license='MIT',
    classifiers=['Development Status :: 2 - Pre-Alpha', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Natural Language :: English', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8'],
    entry_points={"console_scripts": ["xepmts-server = xepmts_server.cli:main"]},
    packages=['xepmts_server', 'xepmts_server.admin', 'xepmts_server.v1', 'xepmts_server.v2', 'xepmts_server.versions'],
    package_dir={"": "."},
    package_data={},
    install_requires=['eve==1.*,>=1.1.5', 'eve-jwt==0.*,>=0.1.9', 'eve-swagger==0.*,>=0.1.3', 'flask-swagger-ui==3.*,>=3.36.0', 'prometheus-flask-exporter==0.*,>=0.18.1', 'toml==0.*,>=0.10.2', 'xeauth==0.1.2', 'xepmts-endpoints==0.*,>=0.1.0'],
    extras_require={"dev": ["bumpversion", "coverage", "dephell", "flake8", "invoke", "isort", "nbsphinx", "pylint", "pytest", "sphinx", "sphinx-material", "tox", "yapf"]},
)
